
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sql.arcdata.microsoft.com
  resources:
  - sqlmanagedinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sqlmi.arc-sql-mi.microsoft.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sqlmi.arc-sql-mi.microsoft.io
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - sqlmi.arc-sql-mi.microsoft.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
