apiVersion: sqlmi.arc-sql-mi.microsoft.io/v1alpha1
kind: Database
metadata:
  name: database-sample
spec:
  # Add fields here
  name: MyDatabase1
  # server: 20.185.3.18
  # port: 1433
  collation: SQL_Latin1_General_CP1_CS_AS
  sqlManagedInstance: jumpstart-sql
  parameterization: forced # options:[simple, forced]
  allowSnapshotIsolation: true # optional
  allowReadCommittedSnapshot: false
  compatibilityLevel: 150 # optional
  # schedule: "0 */12 * * *" # "*/1 * * * *"
  forceUpdate: true
  # credentials:
  #   name: credentials
  #   passwordKey: password
  #   usernameKey: username
